name: dart_audio_intelligence
description: A strongly-typed Dart intelligence layer for audio transcription and analysis via the AssemblyAI API.
version: 0.0.1
publish_to: none # Remove this line when you are ready to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0